src/Entity/Commandes.php
<?php

namespace App\Entity;

use App\Repository\CommandesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandesRepository::class)
 */
class Commandes
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $DateC;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $Heure;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $Vente;

    /**
     * @ORM\ManyToOne(targetEntity=Restaurants::class, inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $restaurant;

    /**
     * @ORM\Column(type="integer")
     */
    private $Montant;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="commandes")
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->DateC;
    }

    public function setDate(\DateTimeInterface $DateC): self
    {
        $this->DateC = $DateC;

        return $this;
    }

    public function getHeure(): ?string
    {
        return $this->Heure;
    }

    public function setHeure(string $Heure): self
    {
        $this->Heure = $Heure;

        return $this;
    }

    public function getVente(): ?string
    {
        return $this->Vente;
    }

    public function setVente(string $Vente): self
    {
        $this->Vente = $Vente;

        return $this;
    }

    public function getRestaurant(): ?Restaurants
    {
        return $this->restaurant;
    }

    public function setRestaurant(?Restaurants $restaurant): self
    {
        $this->restaurant = $restaurant;

        return $this;
    }

    public function getMontant(): ?float
    {
        return $this->Montant;
    }

    public function setMontant(float $Montant): self
    {
        $this->Montant = $Montant;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Entity\Frequence;
use App\Entity\Categories;
use App\Form\FrequenceType;
use App\Form\ProduitMenuType;
use App\Form\ProduitCarteType;
use App\Form\CategoriesMenuType;
use App\Form\CategoriesCarteType;
use App\Repository\SMSRepository;
use App\Repository\UserRepository;
use App\Repository\AchatRepository;
use App\Repository\BanqueRepository;
use App\Repository\HoraireRepository;
use App\Repository\CommandesRepository;
use App\Repository\FrequenceRepository;
use App\Repository\CategoriesRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\ReservationRepository;
use App\Repository\RestaurantsRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class ProfilController extends AbstractController
{

    public function __construct(){
        $this->HORAIRE = [
            "lundi_o_m" => "",
            "lundi_f_m" => "",
            "mardi_o_m" => "",
            "mardi_f_m" => "",
            "mercredi_o_m" => "",
            "mercredi_f_m" => "",
            "jeudi_o_m" => "",
            "jeudi_f_m" => "",
            "vendredi_o_m" => "",
            "vendredi_f_m" => "",
            "samedi_o_m" => "",
            "samedi_f_m" => "",
            "dimanche_o_m" => "",
            "dimanche_f_m" => "",
            "lundi_o_s" => "",
            "lundi_f_s" => "",
            "mardi_o_s" => "",
            "mardi_f_s" => "",
            "mercredi_o_s" => "",
            "mercredi_f_s" => "",
            "jeudi_o_s" => "",
            "jeudi_f_s" => "",
            "vendredi_o_s" => "",
            "vendredi_f_s" => "",
            "samedi_o_s" => "",
            "samedi_f_s" => "",
            "dimanche_o_s" => "",
            "dimanche_f_s" => ""
        ];
    }

    /**
     * @Route("/mon-compte", name="profil")
     */
    public function index(
        Request $request, 
        UserRepository $userRepository, 
        UserPasswordEncoderInterface $encorder, 
        EntityManagerInterface $em, 
        ReservationRepository $reservationREPO, 
        RestaurantsRepository $restaurantsRepository, 
        CategoriesRepository $categRepo, 
        CommandesRepository $commandesRepository, 
        SMSRepository $SMSRepository, 
        AchatRepository $achatRepository, 
        HoraireRepository $HoraireRepository,
        FrequenceRepository $freq,
        BanqueRepository $banqueRepository
        ): Response
    {

        if($this->getUser() === null){
            return $this->redirectToRoute('home');
        }

        $userId = $this->getUser()->getId();
        $reservations = $reservationREPO->selectAllReservation($this->getUser()->getId());

        $commandes = [];

        if($this->isGranted('ROLE_RESTAURANT')) {

            $commandes = $commandesRepository->selectAllCommande($this->getUser()->getRestaurant()->getId());
        } else {

            $commandes = $commandesRepository->selectAllCommandeClient($this->getUser()->getId());
        }

        if($this->isGranted('ROLE_RESTAURANT')) {

            $getRestaurants = $this->getUser()->getRestaurant();

            $options = [
                'reservation' => $getRestaurants->getreservationEnLigne() === true ? 1 : 0,
                'commande' => $getRestaurants->getcommandeEnLigne()  === true ? 1 : 0,
                'sms' => $getRestaurants->getenvoiSMS()  === true ? 1 : 0
            ];

            $categMenu = $categRepo->findCateg($this->getUser()->getRestaurant()->getId(),"menu");
            $categCarte = $categRepo->findCateg($this->getUser()->getRestaurant()->getId(),"carte");

        } else {
            $options = null;

            $categMenu = null;
            $categCarte = null;
        }
       
        //Formulaire mon compte
        if($request->get('submit') == 1){

            if($this->isGranted('ROLE_RESTAURANT')){

                if($request->get('nom_resto') == null || $request->get('zip') == null || $request->get('email') == null || $request->get('telephone') == null || $request->get('ville') == null){

                    $this->addFlash('danger','Certains champs sont vides');
                
                    return $this->redirectToRoute('profil');
                }

            } else {

                if($request->get('nom') == null || $request->get('prenom') == null || $request->get('email') == null || $request->get('telephone') == null){

                    $this->addFlash('danger','Certains champs sont vides');
                    
                    return $this->redirectToRoute('profil');
    
                }
            }


            if(strlen($request->get('telephone')) !== 10){

                $this->addFlash('danger','Attention le numéro de téléphone doit contenir 10 chiffres.');
                
                return $this->redirectToRoute('profil');
            }
         
            $emailExist = $userRepository->emailExist($request->get('email'),$userId);

            if($emailExist > 0){

                $this->addFlash('danger','Vous ne pouvez pas utiliser ce mail.');
                return $this->redirectToRoute('profil');

            }


            if($this->isGranted('ROLE_RESTAURANT')){

                $file = $request->files->get('photo');
                
                if($file !== null){

                    $extensions_valides=["png","jpg","jpeg"];

                    if (!in_array($file->guessExtension(),$extensions_valides)) {

                        $this->addFlash('error', 'Mauvaise extension de fichier !');
                        return $this->redirectToRoute('profil');

                    } else {

                        $fileName = md5(uniqid()).'.'.$file->guessExtension();
                        $file->move($this->getParameter('upload_directory'),$fileName);


                    }
                } else {
                    $fileName = null;
                }


                $userRepository->updateRestaurantProfile(
                    $request->get('email'), 
                    $request->get('telephone'), 
                    $fileName, 
                    $request->get('nom_resto'), 
                    $request->get('zip'), 
                    $request->get('ville'), 
                    $userId
                );

            } else {

                $userRepository->updateAccount(
                    $request->get('nom'), 
                    $request->get('prenom'), 
                    $request->get('email'), 
                    $request->get('telephone'),  
                    $userId
                );
            }

            $this->addFlash('success','Les modifications ont bien été prise en compte.');
                
            return $this->redirectToRoute('profil');
            
        }

        //Formulaire changement mot de passe
        if($request->get('submitPass') == 1){

            $user = $this->getUser();
            $oldPassword = $request->get('old_password');
           
            if($request->get('password_conf') !== $request->get('new_password')){

                $this->addFlash('danger','Attention la confirmation du mot de passe est différente.');
                
                return $this->redirectToRoute('profil');
            }

            if($request->get('old_password') == null || $request->get('password_conf') == null || $request->get('new_password') == null){

                $this->addFlash('danger','Certains champs sont vides');
                
                return $this->redirectToRoute('profil');
            }

            if($encorder->isPasswordValid($user, $oldPassword)){
                $newPassword = $encorder->encodePassword($user, $request->get('new_password'));

                $user->setPassword($newPassword);

                $em->persist($user);
                $em->flush();

                $this->addFlash('success','Le mot de passe à bien été changé.');
                
                return $this->redirectToRoute('profil');
            } else {
                $this->addFlash('danger','L\'ancien mot de passe est incorrect.');
                
                return $this->redirectToRoute('profil');
            }
        }

        //Formulaire Gérant
        if($request->get('submitGerant') == 1){

            if($request->get('nom_gerant') == null || $request->get('telephone_gerant') == null || $request->get('email_gerant') == null){

                $this->addFlash('danger','Certains champs sont vides');
                
                return $this->redirectToRoute('profil');

            }

            $idRestaurant = $this->getUser()->getRestaurant()->getId();

            //Cherche si l'email est pris par un autre utilisateur et gérant
            $emailTakeByUser = $userRepository->emailExist($request->get('email_gerant'),$idRestaurant);
            $emailTakeByGerant = $restaurantsRepository->emailTakeByGerant($request->get('email_gerant'),$idRestaurant);

            if($emailTakeByUser > 0 || $emailTakeByGerant > 0){

                $this->addFlash('danger','Vous ne pouvez pas utiliser ce mail.');
                return $this->redirectToRoute('profil');

            }

            if(strlen($request->get('telephone_gerant')) !== 10){

                $this->addFlash('danger','Attention le numéro de téléphone doit contenir 10 chiffres.');
                
                return $this->redirectToRoute('profil');
            }

            $userRepository->updateGerant(
                $request->get('nom_gerant'),
                $request->get('telephone_gerant'),
                $request->get('email_gerant'),
                $idRestaurant
            );

            $this->addFlash('success','Les informations du gérant ont bien étés prisent en compte.');

templates/profil/partials/categories.carte.form.html.twig
<h6>Carte</h6>
{{ form_start(form, {'attr': {'id': 'categories-carte'} }) }}
    {{ form_widget(form.nom, {'label': ' ', 'attr': {'class': 'form-control','placeholder' : 'Nom'} }) }}
    <button type="submit">Enregistrer</button>
{{ form_end(form) }}


{{ form_start(produitCarteForm, {'attr': {'id': 'categories-carte-produit'} }) }}
    {{ form_widget(produitCarteForm.nom, {'label': ' ', 'attr': {'class': 'form-control','placeholder' : 'Nom'} }) }}
    {{ form_widget(produitCarteForm.prix, {'label': ' ', 'attr': {'class': 'form-control','placeholder' : 'prix'} }) }}
    <select class="form-select" id="categorie-carte" aria-label="Default select example">
        <option selected value="0">Choisir une catégorie</option>
        {% for categorieC in categoriesCarte %}
            <option value="{{ categorieC.id }}">{{ categorieC.nom }}</option>
        {% endfor %}
    </select>
    <button type="submit">Enregistrer</button>
{{ form_end(produitCarteForm) }}
<div id="carte-msg"></div>

templates/profil/partials/categories.menu.form.html.twig
<h6>Menu</h6>
{{ form_start(form, {'attr': {'id': 'categories-menu'} }) }}
    {{ form_widget(form.nom, {'label': ' ', 'attr': {'class': 'form-control','placeholder' : 'Nom'} }) }}
    <button type="submit">Enregistrer</button>
{{ form_end(form) }}

<h6>Menu</h6>
{{ form_start(productForm, {'attr': {'id': 'categories-menu-produit'} }) }}
    {{ form_widget(productForm.nom, {'label': ' ', 'attr': {'class': 'form-control','placeholder' : 'Nom'} }) }}
    {{ form_widget(productForm.prix, {'label': ' ', 'attr': {'class': 'form-control','placeholder' : 'prix'} }) }}
    <select class="form-select" id="categorie-menu" aria-label="Default select example">
        <option selected value="0">Choisir une catégorie</option>
        {% for categorieM in categoriesMenu %}
            <option value="{{ categorieM.id }}">{{ categorieM.nom }}</option>
        {% endfor %}
    </select>
    <button type="submit">Enregistrer</button>
{{ form_end(productForm) }}
<div id="menu-msg"></div>

templates/profil/partials/commandes.list.html.twig
<h5>Commandes</h5>
{# <table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Heure</th>
      <th scope="col">Service</th>
      {% if is_granted('ROLE_CLIENT') %}
        <th scope="col">Nom du restaurant</th>
      {% endif %}
      {% if is_granted('ROLE_RESTAURANT') %}
        <th scope="col">Nom du client</th>
        <th scope="col">Téléphone du client</th>
      {% endif %}
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for commande in commandes %}
      <tr>  
          <th>{{ commande.date_c }}</th>
          <td>{{ commande.heure }}</td>
          <td>{{ commande.vente }}</td>

          {% if is_granted('ROLE_RESTAURANT') %}
            <td>{{ commande.nom_client }} {{ commande.prenom }}</td>
            <td>{{ commande.telephone }}</td>
          {% endif %}

          {% if is_granted('ROLE_CLIENT') %}
            <td>{{ commande.nom }}</td>
          {% endif %}
          

          <td><a href="{{ commande.id }}">Annuler</a></td>
      </tr>
    {% endfor %}
  </tbody>
</table> #}
{# <table class="table">
  <thead>
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Heure</th>
        <th scope="col">Service</th>
        {% if is_granted('ROLE_CLIENT') %}
          <th scope="col">Nom du restaurant</th>
        {% endif %}
        {% if is_granted('ROLE_RESTAURANT') %}
          <th scope="col">Nom du client</th>
          <th scope="col">Téléphone du client</th>
          <th scope="col">Montant</th>
        {% endif %}
        <th scope="col">Actions</th>
      </tr>
      </thead>                   							 
</table> #}
<div class="test">
    <p>Date</p>
    <p>Heure</p>
    <p>Service</p>
    {% if is_granted('ROLE_CLIENT') %}
      <p>Nom du restaurant</p>
    {% endif %}
    {% if is_granted('ROLE_RESTAURANT') %}
      <p>Nom du client</p>
      <p>Téléphone du client</p>
      <p>Montant</p>
    {% endif %}
    <p>Actions</p>
</div>
<div>
{% for commande in commandes %}
  <button class="accordion-c">
    <p>{{ commande.date_c }}</p>
    <p>{{ commande.heure }}</p>
    <p>{{ commande.vente }}</p>

    {% if is_granted('ROLE_RESTAURANT') %}
      <p>{{ commande.nom_client }}</p>
      <p>{{ commande.telephone }}</p>
    {% endif %}

    {% if is_granted('ROLE_CLIENT') %}
        <p>{{ commande.nom }}</p>
    {% endif %}
    {% if is_granted('ROLE_RESTAURANT') %}
      <p>100 €</p>
    {% endif %}

   <a href="{{ commande.id }}">Annuler</a>
  </button>
  <div class="panel">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>   
{% endfor %}   
</div>
    






















{# {% for commande in commandes %}
  <div class="accordion" id="accordionPanelsStayOpenExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="panelsStayOpen-headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
            {{ commande.date_c }} | 
            {{ commande.heure }} | 
            {{ commande.vente }} |

            

            {% if is_granted('ROLE_CLIENT') %}
              | {{ commande.nom }}
            {% endif %}
            
        </button>
      </h2>
      <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
        <div class="accordion-body">
            {% if is_granted('ROLE_RESTAURANT') %}
              {{ commande.nom_client }} {{ commande.prenom }} |
              {{ commande.telephone }}
            {% endif %}
        </div>
      </div>
    </div>  
  </div>  #}
{# {% endfor %} #}

templates/profil/partials/conge.html.twig
  <table data-controller="fermeture" class="table">
    <thead>
      <tr>
        <th scope="col">Date début</th>
        <th scope="col">Date fin</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody id="fermetureTab"></tbody>
  </table>

  <form>
    <label for="inputState" class="form-label">Date début de congé</label>
    <input type="date" id="deb_conge" name="deb_conge" class="form-control" required>
                            
    <label for="inputState" class="mt-3 form-label">Date fin de congé</label>
    <input type="date" id="fin_conge" name="fin_conge" class="form-control" required>

    <button type="submit" id="submitFermeture" name="submit" class="mt-3 btn btn-primary">Valider</button>             
  </form>
  <div id="messageFermeture"></div>

templates/profil/partials/horaire.html.twig
<div class="mt-5">
<p>Laisser vide si le restaurant est fermé.</p>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th id="title" scope="col">Jour</th>
                <th id="title" scope="col" colspan="2">Matin</th>
                <th id="title" scope="col" colspan="2">Soir</th>
            </tr>
        </thead>
        <tbody>
            <tr>
            <form action="{{ path('upd_horaire', {id:id}) }}" method="POST">
                <th scope="row">Lundi</th>
                    <td><input type="time" name="lundi_o_m" value="{{ horaire.lundi_o_m }}"></td>
                    <td><input type="time" name="lundi_f_m" value="{{ horaire.lundi_f_m }}"></td>
                    <td><input type="time" name="lundi_o_s" value="{{ horaire.lundi_o_s }}"></td>
                    <td><input type="time" name="lundi_f_s" value="{{ horaire.lundi_f_s }}"></td>
                </tr>
                <tr>
                <tr>
                <th scope="row">Mardi</th>
                    <td><input type="time" name="mardi_o_m" value="{{ horaire.mardi_o_m }}"></td>
                    <td><input type="time" name="mardi_f_m" value="{{ horaire.mardi_f_m }}"></td>
                    <td><input type="time" name="mardi_o_s" value="{{ horaire.mardi_o_s }}"></td>
                    <td><input type="time" name="mardi_f_s" value="{{ horaire.mardi_f_s }}"></td>
                </tr>
                <tr>
                <tr>
                <th scope="row">Mercredi</th>
                    <td><input type="time" name="mercredi_o_m" value="{{ horaire.mercredi_o_m }}"></td>
                    <td><input type="time" name="mercredi_f_m" value="{{ horaire.mercredi_f_m }}"></td>
                    <td><input type="time" name="mercredi_o_s" value="{{ horaire.mercredi_o_s }}"></td>
                    <td><input type="time" name="mercredi_f_s" value="{{ horaire.mercredi_f_s }}"></td>
                </tr>
                <tr>
                <tr>
                <th scope="row">Jeudi</th>
                    <td><input type="time" name="jeudi_o_m" value="{{ horaire.jeudi_o_m }}"></td>
                    <td><input type="time" name="jeudi_f_m" value="{{ horaire.jeudi_f_m }}"></td>
                    <td><input type="time" name="jeudi_o_s" value="{{ horaire.jeudi_o_s }}"></td>
                    <td><input type="time" name="jeudi_f_s" value="{{ horaire.jeudi_f_s }}"></td>
                </tr>
                <tr>
                <tr>
                <th scope="row">Vendredi</th>
                    <td><input type="time" name="vendredi_o_m" value="{{ horaire.vendredi_o_m }}"></td>
                    <td><input type="time" name="vendredi_f_m" value="{{ horaire.vendredi_f_m }}"></td>
                    <td><input type="time" name="vendredi_o_s" value="{{ horaire.vendredi_o_s }}"></td>
                    <td><input type="time" name="vendredi_f_s" value="{{ horaire.vendredi_f_s }}"></td>
                </tr>
                <tr>
                <tr>
                <th scope="row">Samedi</th>
                    <td><input type="time" name="samedi_o_m" value="{{ horaire.samedi_o_m }}"></td>
                    <td><input type="time" name="samedi_f_m" value="{{ horaire.samedi_f_m }}"></td>
                    <td><input type="time" name="samedi_o_s" value="{{ horaire.samedi_o_s }}"></td>
                    <td><input type="time" name="samedi_f_s" value="{{ horaire.samedi_f_s }}"></td>
                </tr>
                <tr>
                <tr>
                <th scope="row">Dimanche</th>
                    <td><input type="time" name="dimanche_o_m" value="{{ horaire.dimanche_o_m }}"></td>
                    <td><input type="time" name="dimanche_f_m" value="{{ horaire.dimanche_f_m }}"></td>
                    <td><input type="time" name="dimanche_o_s" value="{{ horaire.dimanche_o_s }}"></td>
                    <td><input type="time" name="dimanche_f_s" value="{{ horaire.dimanche_f_s }}"></td>
                </tr>
                <tr>
            </tbody>
        </table>
        <button class="btn btn-primary" type="submit">Sauvegarder</button>
    </form>
</div>

templates/profil/partials/place.html.twig
<table data-controller="places" class="table table-bordered">
            <thead>
              <tr>
                <th scope="col">Date</th>
                <th scope="col">Place réservable</th>
                <th scope="col">Place libérées</th>
                <th scope="col">Places disponibles</th>
                <th scope="col">Places reservées</th>
                <th scope="col">Actions</th>
              </tr>
            </thead>
            <tbody id="bodyPlaces">
            </tbody>
          </table>
          {# Formulaire de définition des places disponibles #}
          <form method="POST" action="{{ path('place_add') }}">
            <label for="inputState" class="mt-3 form-label">Date</label>
            <input type="date" id="date_place" name="date_place" class="form-control" required>

            <label for="inputState" class="mt-3 form-label">Nombre de place réservables</label>
            <input type="number" id="places" name="places" class="form-control" required>

            <input type="hidden" id="idResto-js" value="{{ app.user.restaurant.id }}">
            <button type="submit" id="submitPlaces" class="mt-3 btn btn-primary">Valider</button>
          </form>

      
          <div id="formliberees"></div>

          <div id="places-msg"></div>

         
          

templates/profil/partials/reservations.list.html.twig
<h5>Reservations</h5>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Heure</th>
      <th scope="col">Service</th>
      {% if is_granted('ROLE_CLIENT') %}
        <th scope="col">Nom du restaurant</th>
      {% endif %}
      {% if is_granted('ROLE_RESTAURANT') %}
        <th scope="col">Nom du client</th>
        <th scope="col">Téléphone du client</th>
      {% endif %}
      <th scope="col">Nombre couvert</th>

      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody id="tbody-reservation">
    {% for reservation in reservations %}
      <tr>  
          <th>{{ reservation.date }}</th>
          <td>{{ reservation.horaire }}</td>
          <td>{{ reservation.service }}</td>
          {% if is_granted('ROLE_RESTAURANT') %}
            <td>{{ reservation.nom_client }} {{ reservation.prenom }}</td>
            <td>{{ reservation.telephone }}</td>
          {% endif %}

          {% if is_granted('ROLE_CLIENT') %}
            <td>{{ reservation.nom }}</td>
          {% endif %}
          
          
          <td>{{ reservation.nombre }}</td>
          <td><a href="{{ path('cancel_reservation', {id: reservation.id, uuid: reservation.uuid}) }}" id="cancel-reservation">Annuler</a></td>
      </tr>
    {% endfor %}
  </tbody>
</table>

templates/profil/partials/sms.html.twig
<h5>SMS</h5>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">SMS (Achat + Solde)</th>
      <th scope="col">SMS utilisés</th>
      <th scope="col">SMS restant</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% if sms.id is defined %}
      <tr>  
          <td id="solde">{{ sms.solde }}</td>
          <td id="smsUtilise">{{ sms.smsUtilise }}</td>
          <td id="restant">{{ sms.solde - sms.smsUtilise}}</td>
    {% else %}
      <tr>  
          <td>0</td>
          <td>0</td>
          <td>0</td>
    {% endif %}
          <td><a href="{{ path('reload_sms') }}" id="reloadSMS">Actualiser</a></td>
      </tr>
  </tbody>
</table>


<h5>Achat de SMS</h5>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Quantité SMS</th>
      <th scope="col">Prix TTC</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
     {% for row in achat %}
      <tr>  
          <td>{{ row.quantite }}</td>
          <td>{{ row.prix }}€</td>
          <td>
            <form action="/create-checkout-session" method="POST">
              <input type="hidden" name="idProd" value="{{ row.id }}">
              <button type="submit">Acheter</button>
            </form>
          </td>
      </tr>
     {% endfor %}
  </tbody>
</table>